version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    user: 1000:1000
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /home/atul/Desktop/share/data:/media
      #- /path/to/media2:/media2:ro
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.32:8096